#### 训练集生成

In [2]:
import numpy as np

# 设置随机种子，以便结果可重复
np.random.seed(42)

# 设置样本数
n_samples = 100

# 设置特征数
n_features = 3

# 生成随机数据 （其中可以通过乘和加来得到一个区间内的数据集）
X = np.random.randn(n_samples, n_features)

# 定义真实的权重和偏差(截距)
true_coef = np.array([3, -1,2])
true_intercept = 1

# 生成带有噪声的标签
y = np.dot(X, true_coef) + true_intercept + np.random.randn(n_samples)

# 将数据集分成训练集和测试集
train_ratio = 0.8
train_size = int(n_samples * train_ratio)

X_train, X_test = X[:train_size], X[train_size:]
y_train, y_test = y[:train_size], y[train_size:]

print(X)


[[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]
 [ 1.57921282  0.76743473 -0.46947439]
 [ 0.54256004 -0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024 -1.72491783]
 [-0.56228753 -1.01283112  0.31424733]
 [-0.90802408 -1.4123037   1.46564877]
 [-0.2257763   0.0675282  -1.42474819]
 [-0.54438272  0.11092259 -1.15099358]
 [ 0.37569802 -0.60063869 -0.29169375]
 [-0.60170661  1.85227818 -0.01349722]
 [-1.05771093  0.82254491 -1.22084365]
 [ 0.2088636  -1.95967012 -1.32818605]
 [ 0.19686124  0.73846658  0.17136828]
 [-0.11564828 -0.3011037  -1.47852199]
 [-0.71984421 -0.46063877  1.05712223]
 [ 0.34361829 -1.76304016  0.32408397]
 [-0.38508228 -0.676922    0.61167629]
 [ 1.03099952  0.93128012 -0.83921752]
 [-0.30921238  0.33126343  0.97554513]
 [-0.47917424 -0.18565898 -1.10633497]
 [-1.19620662  0.81252582  1.35624003]
 [-0.07201012  1.0035329   0.36163603]
 [-0.64511975  0.36139561  1.53803657]
 [-0.03582604  1.56464366 -2.6197451 ]
 [ 0.8219025   0.08704707