#### 训练集生成

In [6]:
import numpy as np

# 设置随机种子，以便结果可重复
np.random.seed(42)

# 设置样本数
n_samples = 100

# 设置特征数
n_features = 3

# 生成随机数据 （其中可以通过乘和加来得到一个区间内的数据集）
X = np.random.randn(n_samples, n_features)

# 定义真实的权重和偏差(截距)
true_coef = np.array([3, -1,2])
true_intercept = 1

# 生成带有噪声的标签
y = np.dot(X, true_coef) + true_intercept + np.random.randn(n_samples)

# 将数据集分成训练集和测试集
train_ratio = 0.8
train_size = int(n_samples * train_ratio)

X_train, X_test = X[:train_size], X[train_size:]
y_train, y_test = y[:train_size], y[train_size:]

print(X)


[[  24.83570765   -6.91321506   32.38442691]
 [  76.15149282  -11.70766874  -11.70684785]
 [  78.96064078   38.37173646  -23.4737193 ]
 [  27.12800218  -23.17088464  -23.28648768]
 [  12.09811358  -95.66401223  -86.24589163]
 [ -28.11437646  -50.64155602   15.71236663]
 [ -45.40120378  -70.61518507   73.28243845]
 [ -11.28881502    3.37641023  -71.23740931]
 [ -27.21913623    5.54612949  -57.54967887]
 [  18.78490092  -30.0319345   -14.58468749]
 [ -30.08533061   92.61390923   -0.67486124]
 [ -52.88554645   41.12724561  -61.0421825 ]
 [  10.44317975  -97.98350619  -66.40930244]
 [   9.84306179   36.923329      8.56841406]
 [  -5.78241412  -15.05518478  -73.92609952]
 [ -35.99221042  -23.03193855   52.85611131]
 [  17.18091448  -88.15200777   16.20419847]
 [ -19.25411402  -33.84610002   30.58381444]
 [  51.54997612   46.56400596  -41.96087616]
 [ -15.46061879   16.56317157   48.77725636]
 [ -23.95871189   -9.28294883  -55.3167487 ]
 [ -59.8103312    40.62629112   67.81200143]
 [  -3.600